import {
  COA,
  CompanySettings,
  Department,
  ExchangeRates,
  FixedAssetItem,
  InventoryItem,
  MonthData,
  MonthlyDistribution,
  SalesDeliveryItem,
  SalesInvoiceItem,
  Supplier,
  Customer,
  ItemStock,
  ProductionProcess,
  DailyRate,
  PurchaseRequest,
  PurchaseOrder
} from '../types';

export const DP_MONTHS: (keyof MonthlyDistribution)[] = [
  'Jan', 'Feb', 'Mar', 'Apr', 'Mei', 'Jun', 'Jul', 'Agu', 'Sep', 'Okt', 'Nov', 'Des'
];

export const DEFAULT_DEPARTMENTS: Department[] = [
  { code: 'ACC', name: 'Accounting' },
  { code: 'BAG1', name: 'Bagian 1' },
  { code: 'BAG2', name: 'Bagian 2' },
  { code: 'CF', name: 'Cold Forging' },
  { code: 'ENG', name: 'Production Engineering' },
  { code: 'FIN', name: 'Finishing' },
  { code: 'HRGA', name: 'HRGA' },
  { code: 'MTC', name: 'Maintenance' },
  { code: 'PC', name: 'Production Control' },
  { code: 'PPC', name: 'PPC' },
  { code: 'PUR', name: 'Purnishing' },
  { code: 'QC', name: 'Quality Control' }
];

export const DEFAULT_RATES_BY_YEAR: Record<string, ExchangeRates> = {
  '2026': { IDR: 16273.56, JPY: 142.54, CNY: 0.14, EUR: 0.92 },
  '2025': { IDR: 16150.00, JPY: 140.20, CNY: 0.14, EUR: 0.91 }
};

export const DEFAULT_COA: COA[] = [
  { code: "1000001", name: "Petty Cash - IDR", parent: "", type: "", nature: "debit" },
  { code: "1000002", name: "Petty Cash - USD", parent: "", type: "", nature: "debit" },
  { code: "1000003", name: "Petty Cash - JPY", parent: "", type: "", nature: "debit" },
  { code: "1020001", name: "BII IDR a/c 2232000818", parent: "", type: "", nature: "debit" },
  { code: "1020002", name: "BTM UFJ IDR a/c 665156155", parent: "", type: "", nature: "debit" },
  { code: "1020003", name: "Mizuho IDR", parent: "", type: "", nature: "" },
  { code: "1020004", name: "SMBC IDR a/c1011910401", parent: "", type: "", nature: "" },
  { code: "1020005", name: "Resona IDR a/c 01034864000", parent: "", type: "", nature: "" },
  { code: "1020006", name: "BTM USD A/C 665-894622", parent: "", type: "", nature: "" },
  { code: "1020007", name: "Mizuho USD", parent: "", type: "", nature: "" },
  { code: "1020008", name: "SMBC USD a/c1011910402", parent: "", type: "", nature: "" },
  { code: "1020009", name: "Resona USD a/c 01066333066", parent: "", type: "", nature: "" },
  { code: "1020010", name: "Time deposit IDR - BII", parent: "", type: "", nature: "" },
  { code: "1020012", name: "Danamon IDR 003669932927", parent: "", type: "", nature: "" },
  { code: "1030000", name: "Cash-Bank Transfer (Ayat Silang)", parent: "", type: "", nature: "" },
  { code: "1040001", name: "Account Receivable - USD", parent: "", type: "", nature: "" },
  { code: "1040002", name: "Account Receivable - IDR", parent: "", type: "", nature: "" },
  { code: "1040003", name: "Account Receivable - JPY", parent: "", type: "", nature: "" },
  { code: "1040004", name: "Account Receivable - CNY", parent: "", type: "", nature: "" },
  { code: "1050002", name: "Advance Purchase - IDR", parent: "", type: "", nature: "" },
  { code: "1050003", name: "Advance Purchase - JPY", parent: "", type: "", nature: "" },
  { code: "1050004", name: "Advance Purchase - CNY", parent: "", type: "", nature: "" },
  { code: "1051000", name: "Advance Payment IDR", parent: "", type: "", nature: "" },
  { code: "1051001", name: "Advance Payment USD", parent: "", type: "", nature: "" },
  { code: "1051002", name: "Advance Payment JPY", parent: "", type: "", nature: "" },
  { code: "1060000-2", name: "Other receivable IDR", parent: "", type: "", nature: "" },
  { code: "1060000-3", name: "Interest Receivables", parent: "", type: "", nature: "" },
  { code: "1070000-1", name: "Other Rec.- Related party - USD", parent: "", type: "", nature: "" },
  { code: "1070000-2", name: "Other Rec.- Related party - IDR", parent: "", type: "", nature: "" },
  { code: "1070000-3", name: "Allowance for other receivable impairment", parent: "", type: "", nature: "" },
  { code: "1070000-4", name: "Other Rec.- Related party - JPY", parent: "", type: "", nature: "" },
  { code: "1080001", name: "Inventory - Raw Material", parent: "", type: "", nature: "debit" },
  { code: "1080002", name: "Inventory - in transit", parent: "", type: "", nature: "debit" },
  { code: "1080003", name: "Inventory - WIP", parent: "", type: "", nature: "debit" },
  { code: "1080004", name: "Inventory - Finished Goods", parent: "", type: "", nature: "debit" },
  { code: "1080005", name: "Inventory - Mold & Spareparts", parent: "", type: "", nature: "debit" },
  { code: "1080006", name: "Inventory - Mold & Sparepart in transit", parent: "", type: "", nature: "debit" },
  { code: "1090001", name: "Prepaid Taxes - VAT input", parent: "", type: "", nature: "debit" },
  { code: "1090002", name: "Prepaid Taxes - Prep. tax 22", parent: "", type: "", nature: "debit" },
  { code: "1090004", name: "Prepaid Taxes - Prep. tax 23", parent: "", type: "", nature: "debit" },
  { code: "1100001", name: "Prepaid exp - Rent. Apartment", parent: "", type: "", nature: "debit" },
  { code: "1100002", name: "Prepaid exp - Insurance", parent: "", type: "", nature: "debit" },
  { code: "1100099", name: "Prepaid exp - Others USD", parent: "", type: "", nature: "debit" },
  { code: "1100100", name: "Prepaid exp - Others IDR", parent: "", type: "", nature: "debit" },
  { code: "1100101", name: "Prepaid exp - Others JPY", parent: "", type: "", nature: "debit" },
  { code: "1110002", name: "Building & Factory", parent: "", type: "", nature: "debit" },
  { code: "1110003", name: "Machinery & Equipment", parent: "", type: "", nature: "debit" },
  { code: "1110005", name: "Furniture & Fixtures", parent: "", type: "", nature: "debit" },
  { code: "1120002", name: "Accum Dep - Building & Factory", parent: "", type: "", nature: "credit" },
  { code: "1120003", name: "Accum Dep - Mach & Equipment", parent: "", type: "", nature: "credit" },
  { code: "1120005", name: "Accum Dep - Furniture & Fixt.", parent: "", type: "", nature: "credit" },
  { code: "1120006", name: "Accum Dep - FA Under Cap Lease", parent: "", type: "", nature: "credit" },
  { code: "1160001", name: "Refundable Deposit IDR", parent: "", type: "", nature: "debit" },
  { code: "1160002", name: "Provision for refundable deposit impairment IDR", parent: "", type: "", nature: "credit" },
  { code: "1160004", name: "Refundable Deposit - Sedana", parent: "", type: "", nature: "debit" },
  { code: "1170001", name: "Intangible Fixed Asset", parent: "", type: "", nature: "debit" },
  { code: "1170002", name: "Deffered Charge Landright", parent: "", type: "", nature: "debit" },
  { code: "1180001", name: "Other non-current asset IDR", parent: "", type: "", nature: "debit" },
  { code: "1180002", name: "Other current asset IDR", parent: "", type: "", nature: "debit" },
  { code: "1220000", name: "Right of Use Assets - Accumulated Depreciation", parent: "", type: "", nature: "credit" },
  { code: "2010001", name: "Trade Payable - USD", parent: "", type: "", nature: "credit" },
  { code: "2010002", name: "Trade Payable - IDR", parent: "", type: "", nature: "credit" },
  { code: "2010003", name: "Trade Payable - JPY", parent: "", type: "", nature: "credit" },
  { code: "2010004", name: "Trade Payable - CNY", parent: "", type: "", nature: "credit" },
  { code: "2010005", name: "Trade Payable - PHP", parent: "", type: "", nature: "credit" },
  { code: "2020002", name: "Advance Sales-IDR", parent: "", type: "", nature: "credit" },
  { code: "2020003", name: "Advance Sales-JPY", parent: "", type: "", nature: "credit" },
  { code: "2020004", name: "Advance Sales-CNY", parent: "", type: "", nature: "credit" },
  { code: "2030001", name: "Inc tax payable art 21", parent: "", type: "", nature: "credit" },
  { code: "2030003", name: "VAT Out IDR", parent: "", type: "", nature: "credit" },
  { code: "2030004", name: "Inc tax payable art 26", parent: "", type: "", nature: "credit" },
  { code: "2030005", name: "Inc tax payable art 4(2)", parent: "", type: "", nature: "credit" },
  { code: "2030008", name: "Inc tax payable art 23", parent: "", type: "", nature: "credit" },
  { code: "2030009", name: "Tax payables - others IDR", parent: "", type: "", nature: "credit" },
  { code: "2040001", name: "Accrued expenses-USD", parent: "", type: "", nature: "credit" },
  { code: "2040002", name: "Accrued Expenses-IDR", parent: "", type: "", nature: "credit" },
  { code: "2040003", name: "Accrued expenses-JPY", parent: "", type: "", nature: "credit" },
  { code: "2040004", name: "Accrued expenses-CNY", parent: "", type: "", nature: "credit" },
  { code: "2040005", name: "Accrued interest IDR", parent: "", type: "", nature: "credit" },
  { code: "2040006", name: "Accrued interest USD", parent: "", type: "", nature: "credit" },
  { code: "2070001", name: "Leasing Payable - Current", parent: "", type: "", nature: "credit" },
  { code: "2070002", name: "OTHER PAYABLE", parent: "", type: "", nature: "credit" },
  { code: "2090002", name: "Provision of emp. benefit", parent: "", type: "", nature: "credit" },
  { code: "3000002", name: "Sales - HPPM", parent: "", type: "", nature: "credit" },
  { code: "3000003", name: "Sales - Kaneta Kogyo Co., Ltd", parent: "", type: "", nature: "credit" },
  { code: "3000004", name: "Sales - PT Astra Honda Motor", parent: "", type: "", nature: "credit" },
  { code: "3000006", name: "Sales - PT Honda Trading", parent: "", type: "", nature: "credit" },
  { code: "3000007", name: "Sales - Jatco (Guangzhou)", parent: "", type: "", nature: "credit" },
  { code: "3000008", name: "Sales - Jatco (Mexico)", parent: "", type: "", nature: "credit" },
  { code: "3000009", name: "Sales - Jatco (HQ)", parent: "", type: "", nature: "credit" },
  { code: "3000010", name: "Sales - Kaneta Kogyo Foshan", parent: "", type: "", nature: "credit" },
  { code: "3000012", name: "Sales IDR - PT Aichikiki Autoparts", parent: "", type: "", nature: "credit" },
  { code: "3000013", name: "Sales - PT FCC Indonesia", parent: "", type: "", nature: "credit" },
  { code: "3000014", name: "Sales - Jatco (Thailand)", parent: "", type: "", nature: "credit" },
  { code: "3000015", name: "Sales - FCC Mexico", parent: "", type: "", nature: "credit" },
  { code: "3000017", name: "Sales - Jatco (Suzhou)", parent: "", type: "", nature: "credit" },
  { code: "3000099", name: "Sales - Others", parent: "", type: "", nature: "credit" },
  { code: "5010008", name: "Cost of good sold", parent: "", type: "", nature: "debit" },
  { code: "5200001", name: "WIP Consumed - transfer to FG", parent: "", type: "", nature: "debit" },
  { code: "5200002", name: "WIP Consumed - WIP Consumed", parent: "", type: "", nature: "debit" },
  { code: "5300001", name: "Consump.of mat-Consump. of RM", parent: "Used In Production", type: "", nature: "debit" },
  { code: "5500001", name: "Direct labor cost-Sal&Wages", parent: "Direct Labour", type: "", nature: "debit" },
  { code: "5500002", name: "Direct labor cost-THR/Bonus", parent: "Direct Labour", type: "", nature: "debit" },
  { code: "5500003", name: "Direct labor cost-Welfare", parent: "Direct Labour", type: "", nature: "debit" },
  { code: "5500004", name: "Direct labor cost-Jamsostek", parent: "Direct Labour", type: "", nature: "debit" },
  { code: "5500005", name: "Direct labor cost-tax art. 21", parent: "Direct Labour", type: "", nature: "debit" },
  { code: "5500006", name: "Direct labor cost-Meals exp", parent: "Direct Labour", type: "", nature: "debit" },
  { code: "5500007", name: "Direct labor cost-DPKK", parent: "Direct Labour", type: "", nature: "debit" },
  { code: "5500008", name: "Direct labor cost-Emp. Benefit exp.", parent: "Direct Labour", type: "", nature: "debit" },
  { code: "5500009", name: "Direct Fab cost-Cons. tools", parent: "Used In Production", type: "", nature: "debit" },
  { code: "5500010", name: "Direct Fab cost-Electricity", parent: "Factory overhead", type: "", nature: "debit" },
  { code: "5500011", name: "Direct Fab cost-Fuel,Oil,Lubri", parent: "Used In Production", type: "", nature: "" },
  { code: "5500012", name: "Direct Fab cost-Supervisor fee", parent: "Factory overhead", type: "", nature: "" },
  { code: "5500013", name: "Direct Fab cost-Water supply", parent: "Factory overhead", type: "", nature: "" },
  { code: "5500014", name: "Direct Fab cost-Fact. supplies", parent: "Factory overhead", type: "", nature: "" },
  { code: "5500015", name: "Direct Fab Cost Cons PPC-QC", parent: "Factory overhead", type: "", nature: "" },
  { code: "5500016", name: "Direct Fab Cost Cons PPC-MT", parent: "Factory overhead", type: "", nature: "" },
  { code: "5500018", name: "Direct Fab Cost Cons QC Tools", parent: "Factory overhead", type: "", nature: "" },
  { code: "5500019", name: "Direct Fab Cost Cons MT Tools", parent: "Factory overhead", type: "", nature: "" },
  { code: "5500020", name: "Direct Fab Cost Cons MF Tools", parent: "Factory overhead", type: "", nature: "" },
  { code: "5500021", name: "Direct Fab Cost-Del Equip/GA", parent: "Factory overhead", type: "", nature: "" },
  { code: "5500022", name: "FOH - Insurance", parent: "Factory overhead", type: "", nature: "" },
  { code: "5500023", name: "FOH - Maintenance & Repair", parent: "Factory overhead", type: "", nature: "" },
  { code: "5500024", name: "FOH - Rental & Leasehold", parent: "Factory overhead", type: "", nature: "" },
  { code: "5500026", name: "FOH - Importation fee", parent: "Factory overhead", type: "", nature: "" },
  { code: "5500027", name: "FOH - Depreciation", parent: "Factory overhead", type: "", nature: "" },
  { code: "5500028", name: "FOH - Travel", parent: "Factory overhead", type: "", nature: "" },
  { code: "5500029", name: "FOH - Carburizing", parent: "Factory overhead", type: "", nature: "" },
  { code: "5500032", name: "FOH - Depreciation of Right of Use Assets", parent: "Factory overhead", type: "", nature: "" },
  { code: "5500999", name: "FOH - Others", parent: "Factory overhead", type: "", nature: "" },
  { code: "6010001", name: "G&A - Salary (Director)", parent: "Salary and employees compensation", type: "", nature: "" },
  { code: "6010002", name: "G&A - Salary (Workers)", parent: "Salary and employees compensation", type: "", nature: "" },
  { code: "6010003", name: "G&A - THR / Bonus", parent: "Salary and employees compensation", type: "", nature: "" },
  { code: "6010004", name: "G&A - Welfare", parent: "", type: "", nature: "" },
  { code: "6010005", name: "G&A - Meals", parent: "", type: "", nature: "" },
  { code: "6010006", name: "G&A - Jamsostek", parent: "", type: "", nature: "" },
  { code: "6010008", name: "G&A - Communication exp", parent: "", type: "", nature: "" },
  { code: "6010009", name: "G&A - Postage exp", parent: "", type: "", nature: "" },
  { code: "6010010", name: "G&A - Office Supplies", parent: "", type: "", nature: "" },
  { code: "6010011", name: "G&A - Stationery", parent: "", type: "", nature: "" },
  { code: "6010012", name: "G&A - Consultant fee", parent: "", type: "", nature: "" },
  { code: "6010013", name: "G&A - Rental & Leasehold", parent: "", type: "", nature: "" },
  { code: "6010014", name: "G&A - Insurance", parent: "", type: "", nature: "" },
  { code: "6010015", name: "G&A - Entertainment", parent: "", type: "", nature: "" },
  { code: "6010016", name: "G&A - Travelling exp", parent: "", type: "", nature: "" },
  { code: "6010017", name: "G&A - Bank Charge", parent: "", type: "", nature: "" },
  { code: "6010018", name: "G&A - Repair & Maintenance", parent: "", type: "", nature: "" },
  { code: "6010019", name: "G&A - Royalty", parent: "", type: "", nature: "" },
  { code: "6010021", name: "G&A - Depreciation", parent: "", type: "", nature: "" },
  { code: "6010022", name: "G&A - Inc. tax. 21", parent: "", type: "", nature: "" },
  { code: "6010023", name: "G&A - DPKK", parent: "", type: "", nature: "" },
  { code: "6010024", name: "G&A - Selling Transportation", parent: "", type: "", nature: "" },
  { code: "6010025", name: "G&A - Software Maintenance", parent: "", type: "", nature: "" },
  { code: "6010026", name: "G&A - Membership Fee", parent: "", type: "", nature: "" },
  { code: "6010027", name: "G&A - Emp. Benefit exp.", parent: "", type: "", nature: "" },
  { code: "6010028", name: "G&A - Books & Newspaper", parent: "", type: "", nature: "" },
  { code: "6010029", name: "G&A - Security exp", parent: "", type: "", nature: "" },
  { code: "6010030", name: "G&A - Estate service", parent: "", type: "", nature: "" },
  { code: "6010031", name: "G&A - Documentation Fee", parent: "", type: "", nature: "" },
  { code: "6010032", name: "G&A - Bank Guarantee", parent: "", type: "", nature: "" },
  { code: "6010037", name: "G&A - Accommodation", parent: "", type: "", nature: "" },
  { code: "6010038", name: "G&A - Audit Fee", parent: "", type: "", nature: "" },
  { code: "6010041", name: "G&A - Amortization Intangible Asset", parent: "", type: "", nature: "" },
  { code: "6100042", name: "G&A - Depreciation of Right of Use Assets", parent: "", type: "", nature: "" },
  { code: "7000001", name: "Interest income", parent: "", type: "", nature: "credit" },
  { code: "7000999", name: "Miscellaneous income", parent: "", type: "", nature: "credit" },
  { code: "8000001", name: "Interest expense", parent: "", type: "", nature: "debit" },
  { code: "8000003", name: "Forex exchange Loss (Gain)", parent: "", type: "", nature: "debit" },
  { code: "8000999", name: "Miscellaneous expenses", parent: "", type: "", nature: "debit" },
  // Accounting specific COAs
  { code: "3400007", name: "FOH - Depreciation", parent: "Factory overhead", type: "Expense", nature: "debit" },
  { code: "3400015", name: "FOH - Depreciation of Right of Use", parent: "Factory overhead", type: "Expense", nature: "debit" },
  { code: "3600015", name: "G&A - Postage exp", parent: "General & Administrative", type: "Expense", nature: "debit" },
  { code: "3600020", name: "G&A - Audit Fee", parent: "General & Administrative", type: "Expense", nature: "debit" },
  { code: "3600021", name: "G&A - Consultant fee", parent: "General & Administrative", type: "Expense", nature: "debit" },
  { code: "3600030", name: "G&A - Bank Charge", parent: "General & Administrative", type: "Expense", nature: "debit" },
  { code: "3600032", name: "G&A - Royalty", parent: "General & Administrative", type: "Expense", nature: "debit" },
  { code: "3600033", name: "G&A - Tax & Public Dues", parent: "General & Administrative", type: "Expense", nature: "debit" },
  { code: "3600034", name: "G&A - Depreciation", parent: "General & Administrative", type: "Expense", nature: "debit" },
  { code: "3600035", name: "G&A - Depreciation of Right of Use", parent: "General & Administrative", type: "Expense", nature: "debit" },
  { code: "3600045", name: "G&A - Software Maintenance", parent: "General & Administrative", type: "Expense", nature: "debit" },
  { code: "3600053", name: "G&A - Bank Guarantee", parent: "General & Administrative", type: "Expense", nature: "debit" },
  { code: "3600056", name: "G&A - Training & Development", parent: "General & Administrative", type: "Expense", nature: "debit" },
  { code: "3600062", name: "G&A - Amortization Intangible", parent: "General & Administrative", type: "Expense", nature: "debit" },
  { code: "3800001", name: "Interest expense", parent: "Other Expense", type: "Expense", nature: "debit" },
  { code: "3800006", name: "Other Tax Expense-Principal", parent: "Other Expense", type: "Expense", nature: "debit" },
  { code: "3800007", name: "Other Tax Expense-Penalties", parent: "Other Expense", type: "Expense", nature: "debit" },
  { code: "3800008", name: "Other Tax Expense-Interest", parent: "Other Expense", type: "Expense", nature: "debit" },
  { code: "6000001", name: "Interest income", parent: "Other Income", type: "Income", nature: "credit" }
];

export const DEFAULT_FIXED_ASSET_ITEMS: FixedAssetItem[] = [];

export const SAMPLE_FIXED_ASSETS_FOR_IMPORT: Partial<FixedAssetItem>[] = [
  {
    kiNo: 'KI-2024-001',
    code: 'KI-2024-001',
    invoiceNo: 'INV-2024-0412',
    description: 'CNC Machine Hartford LG-1000 Line 1',
    name: 'CNC Machine Hartford LG-1000 Line 1',
    qty: 1,
    acquisitionDate: '2024-03-10',
    deptCode: 'PROD',
    coaCode: '1110003',
    coaName: 'Fixed Asset - Machinery',
    currency: 'USD',
    originalCost: 72000,
    rate: 1,
    acquisitionCostUSD: 72000,
    value: 72000,
    usd: 72000,
    assetType: 'NEW',
    usefulLifeYears: 6,
    usefulLifeMonths: 72,
    priorAccumDepreciation: 22000,
    monthlyDepreciation: {
      Jan: 1000, Feb: 1000, Mar: 1000, Apr: 1000, May: 1000, Jun: 1000,
      Jul: 1000, Aug: 1000, Sep: 1000, Oct: 1000, Nov: 1000, Dec: 1000
    },
    totalDepreciationYear: 12000,
    accumulatedDepreciationUSD: 34000,
    netBookValueUSD: 38000,
    status: 'Active',
    year: 2026,
    notes: 'Line 1 Main Production'
  },
  {
    kiNo: 'KI-2026-003',
    code: 'KI-2026-003',
    invoiceNo: 'INV-2026-0188',
    description: 'High Precision Spindle Upgrade (Kapitalisasi)',
    name: 'High Precision Spindle Upgrade (Kapitalisasi)',
    qty: 1,
    acquisitionDate: '2026-02-01',
    deptCode: 'PROD',
    coaCode: '1110003',
    coaName: 'Fixed Asset - Machinery',
    currency: 'IDR',
    originalCost: 244103400,
    rate: 16273.56,
    acquisitionCostUSD: 15000,
    value: 244103400,
    usd: 15000,
    assetType: 'CAPITALIZATION',
    parentAssetId: '',
    parentAssetKiNo: 'KI-2024-001',
    parentAssetDescription: 'CNC Machine Hartford LG-1000 Line 1',
    usefulLifeYears: 4,
    usefulLifeMonths: 48,
    priorAccumDepreciation: 0,
    monthlyDepreciation: {
      Jan: 0, Feb: 312.5, Mar: 312.5, Apr: 312.5, May: 312.5, Jun: 312.5,
      Jul: 312.5, Aug: 312.5, Sep: 312.5, Oct: 312.5, Nov: 312.5, Dec: 312.5
    },
    totalDepreciationYear: 3437.5,
    accumulatedDepreciationUSD: 3437.5,
    netBookValueUSD: 11562.5,
    status: 'Active',
    year: 2026,
    notes: 'Kapitalisasi mengikuti sisa masa manfaat mesin induk'
  },
  {
    kiNo: 'KI-2023-019',
    code: 'KI-2023-019',
    invoiceNo: 'INV-2023-0902',
    description: 'Forklift Toyota 3-Ton Electric',
    name: 'Forklift Toyota 3-Ton Electric',
    qty: 2,
    acquisitionDate: '2023-07-01',
    deptCode: 'ENG',
    coaCode: '1110003',
    coaName: 'Fixed Asset - Vehicle',
    currency: 'USD',
    originalCost: 48000,
    rate: 1,
    acquisitionCostUSD: 48000,
    value: 48000,
    usd: 48000,
    assetType: 'NEW',
    usefulLifeYears: 5,
    usefulLifeMonths: 60,
    priorAccumDepreciation: 24000,
    monthlyDepreciation: {
      Jan: 800, Feb: 800, Mar: 800, Apr: 800, May: 800, Jun: 800,
      Jul: 800, Aug: 800, Sep: 800, Oct: 800, Nov: 800, Dec: 800
    },
    totalDepreciationYear: 9600,
    accumulatedDepreciationUSD: 33600,
    netBookValueUSD: 14400,
    status: 'Active',
    year: 2026,
    notes: 'Warehouse & Engineering'
  }
];

export const DEFAULT_COMPANY_SETTINGS: CompanySettings = {
  companyName: 'PT. KANETA INDONESIA',
  logoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsqDiO61u49dXdSR9zGyM9cvmPJOS3-Qj1Q82Md0oVIC6JTDVK0tOnW2iK&s=10',
  address: 'Jl. Maligi VI, Sukaluyu, Telukjambe Timur, Karawang, Jawa Barat 41361'
};

export const INITIAL_SAMPLE_MONTHLY_DATA: MonthData = {
  income: 150000,
  categories: [
    { id: 'cat_1', name: 'Operasional Kantor', budget: 12000 },
    { id: 'cat_2', name: 'Maintenance & Utilitas', budget: 8500 },
    { id: 'cat_3', name: 'Pengembangan & Training', budget: 5000 }
  ],
  debts: [],
  goals: [
    { id: 'goal_1', name: 'Dana Cadangan Darurat Tahunan', targetAmount: 200000, monthlyAllocation: 5000 }
  ],
  expenses: []
};

export const DEFAULT_INVENTORY_ITEMS: InventoryItem[] = [
  // 1. Raw Material (COA 1080001)
  {
    id: 'inv_rm_01',
    itemCode: 'RM-001',
    partNo: 'SPCC-SD-1.2',
    name: 'Steel Coil SPCC-SD 1.2 x 1219mm',
    category: 'raw_material',
    uom: 'KG',
    coaCode: '1080001',
    coaName: 'Inventory - Raw Material',
    location: 'WH-RM-01',
    beginningQty: 12500,
    inQty: 8000,
    outQty: 6500,
    endingQty: 14000,
    minimumStock: 4000,
    currency: 'USD',
    unitCost: 1.15,
    rate: 1,
    unitCostUSD: 1.15,
    totalValueUSD: 16100,
    totalValueIDR: 262004316,
    status: 'Normal',
    notes: 'Bahan baku utama stamping bracket'
  },
  {
    id: 'inv_rm_02',
    itemCode: 'RM-002',
    partNo: 'ADC12-ING',
    name: 'Aluminum Ingot ADC-12 High Purity',
    category: 'raw_material',
    uom: 'KG',
    coaCode: '1080001',
    coaName: 'Inventory - Raw Material',
    location: 'WH-RM-02',
    beginningQty: 6200,
    inQty: 4500,
    outQty: 5100,
    endingQty: 5600,
    minimumStock: 2000,
    currency: 'USD',
    unitCost: 2.45,
    rate: 1,
    unitCostUSD: 2.45,
    totalValueUSD: 13720,
    totalValueIDR: 223273243,
    status: 'Normal',
    notes: 'Casting & machining automotive housing'
  },
  {
    id: 'inv_rm_03',
    itemCode: 'RM-003',
    partNo: 'SUS304-20',
    name: 'Stainless Steel Plate SUS304 2.0x1000x2000mm',
    category: 'raw_material',
    uom: 'SHEET',
    coaCode: '1080001',
    coaName: 'Inventory - Raw Material',
    location: 'WH-RM-03',
    beginningQty: 180,
    inQty: 100,
    outQty: 120,
    endingQty: 160,
    minimumStock: 50,
    currency: 'USD',
    unitCost: 42.00,
    rate: 1,
    unitCostUSD: 42.00,
    totalValueUSD: 6720,
    totalValueIDR: 109358323,
    status: 'Normal',
    notes: 'Plate anti karat exhaust shield'
  },
  {
    id: 'inv_rm_04',
    itemCode: 'RM-004',
    partNo: 'PA66-GF30',
    name: 'Polyamide Resin Granule PA66-GF30 Black',
    category: 'raw_material',
    uom: 'KG',
    coaCode: '1080001',
    coaName: 'Inventory - Raw Material',
    location: 'WH-RM-04',
    beginningQty: 3200,
    inQty: 2000,
    outQty: 2400,
    endingQty: 2800,
    minimumStock: 1000,
    currency: 'USD',
    unitCost: 3.80,
    rate: 1,
    unitCostUSD: 3.80,
    totalValueUSD: 10640,
    totalValueIDR: 173150678,
    status: 'Normal',
    notes: 'Injection molding component'
  },
  {
    id: 'inv_rm_05',
    itemCode: 'RM-005',
    partNo: 'S45C-RD30',
    name: 'Carbon Steel Round Bar S45C Dia 30mm',
    category: 'raw_material',
    uom: 'MTR',
    coaCode: '1080001',
    coaName: 'Inventory - Raw Material',
    location: 'WH-RM-05',
    beginningQty: 450,
    inQty: 300,
    outQty: 480,
    endingQty: 270,
    minimumStock: 300,
    currency: 'USD',
    unitCost: 14.50,
    rate: 1,
    unitCostUSD: 14.50,
    totalValueUSD: 3915,
    totalValueIDR: 63710987,
    status: 'Low Stock',
    notes: 'Perlu Purchase Order baru'
  },

  // 2. Mold & Spare Part (COA 1080005)
  {
    id: 'inv_mld_01',
    itemCode: 'MLD-001',
    partNo: 'DIE-AHM-01',
    name: 'Progressive Die Upper Punch Part #AHM-01',
    category: 'mold_sparepart',
    uom: 'SET',
    coaCode: '1080005',
    coaName: 'Inventory - Mold & Spareparts',
    location: 'WH-MOLD-A1',
    beginningQty: 4,
    inQty: 1,
    outQty: 0,
    endingQty: 5,
    minimumStock: 2,
    currency: 'USD',
    unitCost: 3200.00,
    rate: 1,
    unitCostUSD: 3200.00,
    totalValueUSD: 16000,
    totalValueIDR: 260376960,
    status: 'Normal',
    notes: 'Tooling line press 400T'
  },
  {
    id: 'inv_mld_02',
    itemCode: 'MLD-002',
    partNo: 'PIN-D2-8X80',
    name: 'Punch Pin Tool Steel SKD11/D2 8x80mm',
    category: 'mold_sparepart',
    uom: 'PCS',
    coaCode: '1080005',
    coaName: 'Inventory - Mold & Spareparts',
    location: 'RACK-TOOL-02',
    beginningQty: 85,
    inQty: 50,
    outQty: 35,
    endingQty: 100,
    minimumStock: 40,
    currency: 'USD',
    unitCost: 18.50,
    rate: 1,
    unitCostUSD: 18.50,
    totalValueUSD: 1850,
    totalValueIDR: 30106086,
    status: 'Normal',
    notes: 'Suku cadang habis pakai die stamping'
  },
  {
    id: 'inv_mld_03',
    itemCode: 'MLD-003',
    partNo: 'SPR-HL-30100',
    name: 'Heavy Duty Die Spring Red 30x100mm',
    category: 'mold_sparepart',
    uom: 'PCS',
    coaCode: '1080005',
    coaName: 'Inventory - Mold & Spareparts',
    location: 'RACK-TOOL-03',
    beginningQty: 60,
    inQty: 20,
    outQty: 45,
    endingQty: 35,
    minimumStock: 30,
    currency: 'USD',
    unitCost: 12.00,
    rate: 1,
    unitCostUSD: 12.00,
    totalValueUSD: 420,
    totalValueIDR: 6834895,
    status: 'Normal',
    notes: 'Spring press stripper'
  },
  {
    id: 'inv_mld_04',
    itemCode: 'MLD-004',
    partNo: 'HYD-SEAL-300',
    name: 'Hydraulic Cylinder Seal Kit Press 300T',
    category: 'mold_sparepart',
    uom: 'SET',
    coaCode: '1080005',
    coaName: 'Inventory - Mold & Spareparts',
    location: 'CAB-MTC-01',
    beginningQty: 6,
    inQty: 4,
    outQty: 5,
    endingQty: 5,
    minimumStock: 3,
    currency: 'USD',
    unitCost: 145.00,
    rate: 1,
    unitCostUSD: 145.00,
    totalValueUSD: 725,
    totalValueIDR: 11798331,
    status: 'Normal',
    notes: 'Spare part maintenance mesin Komatsu'
  },
  {
    id: 'inv_mld_05',
    itemCode: 'MLD-005',
    partNo: 'EM-4F-10MM',
    name: 'Carbide End Mill 4-Flute TiAlN 10mm',
    category: 'mold_sparepart',
    uom: 'PCS',
    coaCode: '1080005',
    coaName: 'Inventory - Mold & Spareparts',
    location: 'RACK-TOOL-01',
    beginningQty: 24,
    inQty: 30,
    outQty: 40,
    endingQty: 14,
    minimumStock: 20,
    currency: 'USD',
    unitCost: 28.00,
    rate: 1,
    unitCostUSD: 28.00,
    totalValueUSD: 392,
    totalValueIDR: 6379236,
    status: 'Low Stock',
    notes: 'Mata pisau CNC Milling'
  },

  // 3. Work In Process (COA 1080003)
  {
    id: 'inv_wip_01',
    itemCode: 'WIP-001',
    partNo: 'AHM-BRK-OP1',
    name: 'Stamped Front Bracket Op-10 Blanking',
    category: 'wip',
    uom: 'PCS',
    coaCode: '1080003',
    coaName: 'Inventory - WIP',
    location: 'LINE-STAMP-1',
    beginningQty: 4200,
    inQty: 12000,
    outQty: 11500,
    endingQty: 4700,
    minimumStock: 2000,
    currency: 'USD',
    unitCost: 1.85,
    rate: 1,
    unitCostUSD: 1.85,
    totalValueUSD: 8695,
    totalValueIDR: 141498604,
    status: 'Normal',
    notes: 'Siap proses bending Op-20'
  },
  {
    id: 'inv_wip_02',
    itemCode: 'WIP-002',
    partNo: 'JAT-SFT-OP2',
    name: 'Turned Transmission Input Shaft Op-20 CNC',
    category: 'wip',
    uom: 'PCS',
    coaCode: '1080003',
    coaName: 'Inventory - WIP',
    location: 'LINE-CNC-2',
    beginningQty: 1800,
    inQty: 5000,
    outQty: 4600,
    endingQty: 2200,
    minimumStock: 1000,
    currency: 'USD',
    unitCost: 4.60,
    rate: 1,
    unitCostUSD: 4.60,
    totalValueUSD: 10120,
    totalValueIDR: 164688427,
    status: 'Normal',
    notes: 'Menunggu proses hobbing gigi gear'
  },
  {
    id: 'inv_wip_03',
    itemCode: 'WIP-003',
    partNo: 'FCC-PLT-OP3',
    name: 'Heat Treated Clutch Pressure Plate Op-30',
    category: 'wip',
    uom: 'PCS',
    coaCode: '1080003',
    coaName: 'Inventory - WIP',
    location: 'LINE-HT-1',
    beginningQty: 850,
    inQty: 3200,
    outQty: 3400,
    endingQty: 650,
    minimumStock: 800,
    currency: 'USD',
    unitCost: 6.20,
    rate: 1,
    unitCostUSD: 6.20,
    totalValueUSD: 4030,
    totalValueIDR: 65582447,
    status: 'Low Stock',
    notes: 'Percepatan oven tempering diperlukan'
  },
  {
    id: 'inv_wip_04',
    itemCode: 'WIP-004',
    partNo: 'HPPM-SPCR-WIP',
    name: 'Sub-Assy Collar Spacer Ultrasonic Cleaned',
    category: 'wip',
    uom: 'PCS',
    coaCode: '1080003',
    coaName: 'Inventory - WIP',
    location: 'LINE-WASH-1',
    beginningQty: 3100,
    inQty: 8000,
    outQty: 7500,
    endingQty: 3600,
    minimumStock: 1500,
    currency: 'USD',
    unitCost: 1.35,
    rate: 1,
    unitCostUSD: 1.35,
    totalValueUSD: 4860,
    totalValueIDR: 79089502,
    status: 'Normal',
    notes: 'Siap transfer ke Final Inspection'
  },

  // 4. Finish Good (COA 1080004)
  {
    id: 'inv_fg_01',
    itemCode: 'FG-001',
    partNo: '50100-KNT-001',
    name: 'Flange Bracket Front Engine Mounting',
    category: 'finish_good',
    uom: 'PCS',
    coaCode: '1080004',
    coaName: 'Inventory - Finished Goods',
    location: 'WH-FG-A1',
    beginningQty: 5500,
    inQty: 11500,
    outQty: 12200,
    endingQty: 4800,
    minimumStock: 2500,
    currency: 'USD',
    unitCost: 3.40,
    rate: 1,
    unitCostUSD: 3.40,
    totalValueUSD: 16320,
    totalValueIDR: 265584500,
    status: 'Normal',
    notes: 'Siap delivery ke PT Astra Honda Motor'
  },
  {
    id: 'inv_fg_02',
    itemCode: 'FG-002',
    partNo: '31040-JAT-002',
    name: 'Auto Transmission Valve Body Housing',
    category: 'finish_good',
    uom: 'PCS',
    coaCode: '1080004',
    coaName: 'Inventory - Finished Goods',
    location: 'WH-FG-A2',
    beginningQty: 1950,
    inQty: 4600,
    outQty: 4800,
    endingQty: 1750,
    minimumStock: 1000,
    currency: 'USD',
    unitCost: 8.90,
    rate: 1,
    unitCostUSD: 8.90,
    totalValueUSD: 15575,
    totalValueIDR: 253460693,
    status: 'Normal',
    notes: 'Jatco export order standard'
  },
  {
    id: 'inv_fg_03',
    itemCode: 'FG-003',
    partNo: '22100-FCC-003',
    name: 'Clutch Pressure Plate Disc 220mm',
    category: 'finish_good',
    uom: 'PCS',
    coaCode: '1080004',
    coaName: 'Inventory - Finished Goods',
    location: 'WH-FG-B1',
    beginningQty: 1200,
    inQty: 3400,
    outQty: 3700,
    endingQty: 900,
    minimumStock: 1200,
    currency: 'USD',
    unitCost: 11.50,
    rate: 1,
    unitCostUSD: 11.50,
    totalValueUSD: 10350,
    totalValueIDR: 168431346,
    status: 'Low Stock',
    notes: 'Stok di bawah minimum buffer FCC'
  },
  {
    id: 'inv_fg_04',
    itemCode: 'FG-004',
    partNo: '10440-HPPM-004',
    name: 'Precision Spacer Shaft Collar',
    category: 'finish_good',
    uom: 'PCS',
    coaCode: '1080004',
    coaName: 'Inventory - Finished Goods',
    location: 'WH-FG-B2',
    beginningQty: 6400,
    inQty: 7500,
    outQty: 8100,
    endingQty: 5800,
    minimumStock: 3000,
    currency: 'USD',
    unitCost: 2.25,
    rate: 1,
    unitCostUSD: 2.25,
    totalValueUSD: 13050,
    totalValueIDR: 212369958,
    status: 'Normal',
    notes: 'HPPM Kanban batch shipment'
  },
  {
    id: 'inv_fg_05',
    itemCode: 'FG-005',
    partNo: '63200-AKI-005',
    name: 'Stamping Cross Member Lower Rear',
    category: 'finish_good',
    uom: 'PCS',
    coaCode: '1080004',
    coaName: 'Inventory - Finished Goods',
    location: 'WH-FG-C1',
    beginningQty: 2400,
    inQty: 4200,
    outQty: 4100,
    endingQty: 2500,
    minimumStock: 1500,
    currency: 'USD',
    unitCost: 6.80,
    rate: 1,
    unitCostUSD: 6.80,
    totalValueUSD: 17000,
    totalValueIDR: 276650520,
    status: 'Normal',
    notes: 'Aichikiki delivery batch'
  }
];

export const DEFAULT_SALES_DELIVERY_ITEMS: SalesDeliveryItem[] = [
  {
    id: 'do_2026_001',
    deliveryNo: 'DO/2026/03/001',
    poNumber: 'PO-AHM-2026-042',
    deliveryDate: '2026-03-15',
    customer: 'PT Astra Honda Motor',
    partNo: '10110-AHM-001',
    itemName: 'Flange Collar Comp 12mm',
    qty: 5000,
    uom: 'PCS',
    vehiclePlate: 'B 9842 TYN',
    driverName: 'Budi Santoso',
    destinationAddress: 'Plant 3 Cikarang Barat, Kawasan Industri MM2100',
    recipientName: 'Hendra (Incoming QC AHM)',
    status: 'Received',
    notes: 'Pengiriman batch 1 tepat waktu',
    invoiced: true,
    invoiceNo: 'INV/2026/03/0018',
    unitPriceUSD: 3.50,
    totalAmountUSD: 17500
  },
  {
    id: 'do_2026_002',
    deliveryNo: 'DO/2026/03/002',
    poNumber: 'PO-JAT-2026-118',
    deliveryDate: '2026-03-16',
    customer: 'Jatco (Guangzhou)',
    partNo: '24100-JAT-002',
    itemName: 'Primary Drive Gear 24T',
    qty: 2500,
    uom: 'PCS',
    vehiclePlate: 'B 9120 URF (Container 20ft)',
    driverName: 'Agus Setiawan',
    destinationAddress: 'Tanjung Priok Port (Ocean Freight to Guangzhou)',
    recipientName: 'Forwarder Sinotrans',
    status: 'Delivered',
    notes: 'Dokumen BL & COO terlampir',
    invoiced: true,
    invoiceNo: 'INV/2026/03/0019',
    unitPriceUSD: 8.20,
    totalAmountUSD: 20500
  },
  {
    id: 'do_2026_003',
    deliveryNo: 'DO/2026/03/003',
    poNumber: 'PO-FCC-2026-067',
    deliveryDate: '2026-03-18',
    customer: 'PT FCC Indonesia',
    partNo: '31200-FCC-003',
    itemName: 'Clutch Center Boss Plate',
    qty: 1200,
    uom: 'PCS',
    vehiclePlate: 'B 9553 VMA',
    driverName: 'Dedi Kurniawan',
    destinationAddress: 'Kawasan Industri KIIC Lot C-4, Karawang',
    recipientName: 'Wahyudi (Receiving FCC)',
    status: 'In Transit',
    notes: 'Sedang menuju KIIC Karawang',
    invoiced: false,
    unitPriceUSD: 11.50,
    totalAmountUSD: 13800
  },
  {
    id: 'do_2026_004',
    deliveryNo: 'DO/2026/03/004',
    poNumber: 'PO-HPPM-2026-210',
    deliveryDate: '2026-03-19',
    customer: 'HPPM',
    partNo: '10440-HPPM-004',
    itemName: 'Precision Spacer Shaft Collar',
    qty: 4000,
    uom: 'PCS',
    vehiclePlate: 'B 9781 BXR',
    driverName: 'Rudi Hartono',
    destinationAddress: 'Kawasan Industri Indotaisei Cikampek Sector 1A',
    recipientName: 'Logistics HPPM',
    status: 'Scheduled',
    notes: 'Dijadwalkan jam 09:00 WIB',
    invoiced: false,
    unitPriceUSD: 2.25,
    totalAmountUSD: 9000
  },
  {
    id: 'do_2026_005',
    deliveryNo: 'DO/2026/03/005',
    poNumber: 'PO-AKI-2026-095',
    deliveryDate: '2026-03-20',
    customer: 'PT Aichikiki Autoparts',
    partNo: '63200-AKI-005',
    itemName: 'Stamping Cross Member Lower Rear',
    qty: 1500,
    uom: 'PCS',
    vehiclePlate: 'B 9482 TYN',
    driverName: 'Budi Santoso',
    destinationAddress: 'Kawasan Greenland International Industrial Center (GIIC) Cikarang',
    recipientName: 'Siti Rahma (Warehouse AKI)',
    status: 'Scheduled',
    notes: 'Kanban delivery cycle 2',
    invoiced: false,
    unitPriceUSD: 6.80,
    totalAmountUSD: 10200
  }
];

export const DEFAULT_SALES_INVOICE_ITEMS: SalesInvoiceItem[] = [
  {
    id: 'inv_2026_001',
    invoiceNo: 'INV/2026/03/0018',
    taxInvoiceNo: '010.002-26.77192831',
    deliveryNo: 'DO/2026/03/001',
    poNumber: 'PO-AHM-2026-042',
    invoiceDate: '2026-03-15',
    dueDate: '2026-04-15',
    customer: 'PT Astra Honda Motor',
    customerTaxId: '01.328.948.2-054.000',
    customerAddress: 'Jl. Laksda Yos Sudarso, Sunter 1, Jakarta Utara 14350',
    description: 'Penjualan 5,000 PCS Flange Collar Comp 12mm (Part: 10110-AHM-001)',
    currency: 'USD',
    rate: 16273.56,
    subtotal: 17500,
    taxRatePercent: 11,
    taxAmount: 1925,
    totalAmount: 19425,
    totalAmountUSD: 19425,
    totalAmountIDR: 316114903,
    status: 'Paid',
    paymentDate: '2026-04-10',
    bankAccount: 'BTM USD A/C 665-894622',
    notes: 'Lunas via transfer MT103'
  },
  {
    id: 'inv_2026_002',
    invoiceNo: 'INV/2026/03/0019',
    taxInvoiceNo: '010.002-26.77192832',
    deliveryNo: 'DO/2026/03/002',
    poNumber: 'PO-JAT-2026-118',
    invoiceDate: '2026-03-16',
    dueDate: '2026-04-30',
    customer: 'Jatco (Guangzhou)',
    customerTaxId: '91440101MA59BXXX',
    customerAddress: 'Huadu District, Guangzhou, Guangdong, China',
    description: 'Export 2,500 PCS Primary Drive Gear 24T (Part: 24100-JAT-002)',
    currency: 'USD',
    rate: 16273.56,
    subtotal: 20500,
    taxRatePercent: 0,
    taxAmount: 0,
    totalAmount: 20500,
    totalAmountUSD: 20500,
    totalAmountIDR: 333607980,
    status: 'Sent',
    bankAccount: 'Mizuho USD A/C 202-991823',
    notes: 'Kawasan Berikat / Ekspor PPN 0%'
  },
  {
    id: 'inv_2026_003',
    invoiceNo: 'INV/2026/02/0012',
    taxInvoiceNo: '010.002-26.77192750',
    deliveryNo: 'DO/2026/02/088',
    poNumber: 'PO-HPPM-2026-155',
    invoiceDate: '2026-02-10',
    dueDate: '2026-03-10',
    customer: 'HPPM',
    customerTaxId: '01.554.219.0-408.000',
    customerAddress: 'Kawasan Industri Indotaisei Cikampek, Karawang',
    description: 'Penjualan 8,000 PCS Precision Spacer Shaft Collar',
    currency: 'USD',
    rate: 16273.56,
    subtotal: 18000,
    taxRatePercent: 11,
    taxAmount: 1980,
    totalAmount: 19980,
    totalAmountUSD: 19980,
    totalAmountIDR: 325145729,
    status: 'Overdue',
    bankAccount: 'SMBC USD a/c 1011910402',
    notes: 'Jatuh tempo terlewati - follow up ke Purchasing HPPM'
  }
];

// ==========================================
// Master Data Defaults
// ==========================================

export const DEFAULT_SUPPLIERS: Supplier[] = [
  {
    id: 'sup_001',
    code: 'SUP-001',
    name: 'PT Krakatau Steel (Persero) Tbk',
    contactPerson: 'Bambang Triyono (Sales Eng)',
    phone: '+62 254 371111',
    email: 'sales.industrial@krakatausteel.com',
    address: 'Kawasan Industri Krakatau Steel, Jl. Industri No. 5',
    city: 'Cilegon, Banten',
    paymentTerms: 'NET 45',
    npwp: '01.000.013.3-051.000',
    currency: 'IDR',
    isActive: true,
    notes: 'Supplier utama Raw Material Steel Rod S45C & SCr420H'
  },
  {
    id: 'sup_002',
    code: 'SUP-002',
    name: 'PT Daido Steel Indonesia',
    contactPerson: 'Kenji Takahashi / Linda W.',
    phone: '+62 21 8972100',
    email: 'order@daido-steel.co.id',
    address: 'Kawasan Industri MM2100 Blok C-3, Cikarang Barat',
    city: 'Bekasi, Jawa Barat',
    paymentTerms: 'NET 30',
    npwp: '01.554.120.4-413.000',
    currency: 'USD',
    isActive: true,
    notes: 'Supplier Special Steel & Alloy Rods untuk Cold Forging'
  },
  {
    id: 'sup_003',
    code: 'SUP-003',
    name: 'PT Sumitomo Bakelite Indonesia',
    contactPerson: 'Agus Setiawan (Tech Sales)',
    phone: '+62 21 8935400',
    email: 'sales@sumibe.co.id',
    address: 'Kawasan Industri GIIC Blok AA No. 12, Kota Deltamas',
    city: 'Cikarang Pusat, Bekasi',
    paymentTerms: 'NET 30',
    npwp: '01.325.889.1-413.000',
    currency: 'USD',
    isActive: true,
    notes: 'Bahan baku Polycarbonate & Engineering Plastic Resins'
  },
  {
    id: 'sup_004',
    code: 'SUP-004',
    name: 'CV Surya Teknik Mandiri',
    contactPerson: 'Hendra Gunawan',
    phone: '+62 21 89831102',
    email: 'suryateknik.cikarang@gmail.com',
    address: 'Jl. Raya Industri Pasir Gombong No. 88',
    city: 'Cikarang Utara, Bekasi',
    paymentTerms: 'NET 14',
    npwp: '02.441.980.2-413.000',
    currency: 'IDR',
    isActive: true,
    notes: 'Vendor Machining, Dies, Cutting Tools, & Maintenance Sparepart'
  },
  {
    id: 'sup_005',
    code: 'SUP-005',
    name: 'PT Idemitsu Lube Techno Indonesia',
    contactPerson: 'Dwi Raharjo',
    phone: '+62 21 8971200',
    email: 'industrial-sales@idemitsu.co.id',
    address: 'Kawasan Industri KIIC Lot N-1, Telukjambe Barat',
    city: 'Karawang, Jawa Barat',
    paymentTerms: 'NET 30',
    npwp: '01.662.901.6-408.000',
    currency: 'IDR',
    isActive: true,
    notes: 'Oli Forging Lube, Coolant Cutting Oil, & Hydraulic Fluid'
  }
];

export const DEFAULT_CUSTOMERS: Customer[] = [
  {
    id: 'cust_001',
    code: 'CUST-001',
    name: 'PT Toyota Motor Manufacturing Indonesia',
    contactPerson: 'Budi Santoso (Purchasing Dept)',
    phone: '+62 21 6515551',
    email: 'procurement.tmm@toyota.co.id',
    address: 'Jl. Laks. Yos Sudarso, Sunter II',
    city: 'Jakarta Utara',
    paymentTerms: 'NET 60',
    npwp: '01.000.014.1-092.000',
    currency: 'USD',
    isActive: true,
    notes: 'Tier-1 Automotive OEM (Transmission Components)'
  },
  {
    id: 'cust_002',
    code: 'CUST-002',
    name: 'PT Astra Daihatsu Motor',
    contactPerson: 'Rian Kurniawan (Part Logistics)',
    phone: '+62 21 6510300',
    email: 'supply.chain@daihatsu.astra.co.id',
    address: 'Kawasan Industri Suryacipta Kav. 1-10',
    city: 'Karawang Timur',
    paymentTerms: 'NET 45',
    npwp: '01.309.221.7-007.000',
    currency: 'IDR',
    isActive: true,
    notes: 'Drive Pinion & Engine Shaft Assembly'
  },
  {
    id: 'cust_003',
    code: 'CUST-003',
    name: 'Jatco (Guangzhou) Automatic Transmission Ltd',
    contactPerson: 'Li Wei / Export Team',
    phone: '+86 20 3680 9988',
    email: 'overseas-purchasing@jatco-gz.com',
    address: 'No. 8 Huadu Auto City Avenue, Huadu District',
    city: 'Guangzhou, Guangdong, China',
    paymentTerms: 'NET 45',
    npwp: '91440101MA59BXXX',
    currency: 'USD',
    isActive: true,
    notes: 'Direct Export Customer (Primary Drive Gear)'
  },
  {
    id: 'cust_004',
    code: 'CUST-004',
    name: 'PT Denso Indonesia',
    contactPerson: 'Eko Prasetyo (Buyer Section)',
    phone: '+62 21 8980303',
    email: 'eko.prasetyo@denso.co.id',
    address: 'Kawasan Industri MM2100 Blok KK-1',
    city: 'Cikarang Barat, Bekasi',
    paymentTerms: 'NET 30',
    npwp: '01.320.449.9-413.000',
    currency: 'USD',
    isActive: true,
    notes: 'HVAC Aircon Pulley & Alternator Rotor Pins'
  },
  {
    id: 'cust_005',
    code: 'CUST-005',
    name: 'PT Yamaha Indonesia Motor Mfg',
    contactPerson: 'Surya Dharma',
    phone: '+62 21 4607880',
    email: 'purchasing@yamaha-motor.co.id',
    address: 'Jl. DR. KRT. Radjiman Widyodiningrat, Pulogadung',
    city: 'Jakarta Timur',
    paymentTerms: 'NET 30',
    npwp: '01.302.112.5-003.000',
    currency: 'IDR',
    isActive: true,
    notes: 'Motorcycle Crankshaft & Sprocket Gears'
  }
];

export const DEFAULT_ITEM_STOCKS: ItemStock[] = [
  {
    id: 'item_001',
    code: 'RM-S45C-D28',
    name: 'Round Steel Bar S45C Dia 28mm x 6000mm',
    category: 'raw_material',
    uom: 'Kg',
    inventoryAccountCode: '1080001',
    inventoryAccountName: 'Raw Material',
    expenseAccountCode: '5100001',
    expenseAccountName: 'Raw Material Expense / HPP',
    minimumStock: 5000,
    safetyStock: 8000,
    standardCost: 1.45,
    standardPrice: 0,
    currency: 'USD',
    location: 'WH-RM-RACK-01',
    isActive: true,
    notes: 'Material utama Cold Forging shaft gear',
    suppliers: [
      {
        supplierId: 'sup_001',
        supplierCode: 'SUP-001',
        supplierName: 'PT Krakatau Steel (Persero) Tbk',
        price: 23500,
        currency: 'IDR',
        leadTimeDays: 14,
        isPrimary: true,
        notes: 'Minimal order 3 Ton, sertifikat uji tarik JIS G4051'
      },
      {
        supplierId: 'sup_002',
        supplierCode: 'SUP-002',
        supplierName: 'PT Daido Steel Indonesia',
        price: 1.45,
        currency: 'USD',
        leadTimeDays: 7,
        isPrimary: false,
        notes: 'Imported high grade S45C, toleransi presisi h9'
      },
      {
        supplierId: 'sup_004',
        supplierCode: 'SUP-004',
        supplierName: 'CV Surya Teknik Mandiri',
        price: 24200,
        currency: 'IDR',
        leadTimeDays: 3,
        isPrimary: false,
        notes: 'Gudang lokal Cikarang, pengiriman darurat 2-3 hari'
      }
    ]
  },
  {
    id: 'item_002',
    code: 'RM-SCR420-D32',
    name: 'Steel Rod SCr420H Dia 32mm Annealed',
    category: 'raw_material',
    uom: 'Kg',
    inventoryAccountCode: '1080001',
    inventoryAccountName: 'Raw Material',
    expenseAccountCode: '5100001',
    expenseAccountName: 'Raw Material Expense / HPP',
    minimumStock: 4000,
    safetyStock: 6500,
    standardCost: 1.62,
    standardPrice: 0,
    currency: 'USD',
    location: 'WH-RM-RACK-02',
    isActive: true,
    notes: 'Alloy steel untuk carburizing heat treatment',
    suppliers: [
      {
        supplierId: 'sup_002',
        supplierCode: 'SUP-002',
        supplierName: 'PT Daido Steel Indonesia',
        price: 1.62,
        currency: 'USD',
        leadTimeDays: 10,
        isPrimary: true,
        notes: 'Spheroidized annealed, ideal untuk cold extrusion forging'
      },
      {
        supplierId: 'sup_001',
        supplierCode: 'SUP-001',
        supplierName: 'PT Krakatau Steel (Persero) Tbk',
        price: 26000,
        currency: 'IDR',
        leadTimeDays: 14,
        isPrimary: false,
        notes: 'Standard alloy JIS G4053'
      }
    ]
  },
  {
    id: 'item_003',
    code: 'MLD-CF-P24T',
    name: 'Punch Die Cold Forging 24T Gear (Tungsten Carbide)',
    category: 'mold_sparepart',
    uom: 'Set',
    inventoryAccountCode: '1080005',
    inventoryAccountName: 'Mold & Spare Part',
    expenseAccountCode: '5100003',
    expenseAccountName: 'Maintenance & Tooling Expense',
    minimumStock: 2,
    safetyStock: 4,
    standardCost: 850.00,
    standardPrice: 0,
    currency: 'USD',
    location: 'WH-TOOL-ROOM-A',
    isActive: true,
    notes: 'Tooling khusus mesin Forging CF-800Ton',
    suppliers: [
      {
        supplierId: 'sup_002',
        supplierCode: 'SUP-002',
        supplierName: 'PT Daido Steel Indonesia',
        price: 850.00,
        currency: 'USD',
        leadTimeDays: 21,
        isPrimary: true,
        notes: 'Imported Carbide Insert Japan quality'
      },
      {
        supplierId: 'sup_004',
        supplierCode: 'SUP-004',
        supplierName: 'CV Surya Teknik Mandiri',
        price: 13800000,
        currency: 'IDR',
        leadTimeDays: 10,
        isPrimary: false,
        notes: 'Fabrikasi lokal Wire EDM & Vacuum Hardening'
      }
    ]
  },
  {
    id: 'item_004',
    code: 'WIP-CF-BLANK24',
    name: 'Forged Blank Gear 24T (Pre-machined)',
    category: 'wip',
    uom: 'Pcs',
    inventoryAccountCode: '1080003',
    inventoryAccountName: 'Work In Process',
    expenseAccountCode: '5100001',
    expenseAccountName: 'Raw Material Expense / HPP',
    minimumStock: 1500,
    safetyStock: 3000,
    standardCost: 4.80,
    standardPrice: 0,
    currency: 'USD',
    location: 'LINE-CF-BUFFER',
    isActive: true,
    notes: 'Hasil forging siap proses bubut CNC & hobbing',
    suppliers: [
      {
        supplierId: 'sup_004',
        supplierCode: 'SUP-004',
        supplierName: 'CV Surya Teknik Mandiri',
        price: 78000,
        currency: 'IDR',
        leadTimeDays: 5,
        isPrimary: true,
        notes: 'Jasa bubut roughing & chamfer subcon'
      }
    ]
  },
  {
    id: 'item_005',
    code: 'FG-GEAR-24T',
    name: 'Primary Drive Gear 24T (Part 24100-JAT-002)',
    category: 'finish_good',
    uom: 'Pcs',
    inventoryAccountCode: '1080004',
    inventoryAccountName: 'Finish Good',
    expenseAccountCode: '5100001',
    expenseAccountName: 'Raw Material Expense / HPP',
    minimumStock: 1000,
    safetyStock: 2500,
    standardCost: 6.20,
    standardPrice: 8.20,
    currency: 'USD',
    location: 'WH-FG-RACK-B3',
    isActive: true,
    notes: 'Produk ekspor Jatco Guangzhou OEM standard',
    suppliers: [
      {
        supplierId: 'sup_004',
        supplierCode: 'SUP-004',
        supplierName: 'CV Surya Teknik Mandiri',
        price: 98000,
        currency: 'IDR',
        leadTimeDays: 7,
        isPrimary: false,
        notes: 'Subkontrak proses carburizing heat treatment & finishing'
      }
    ]
  },
  {
    id: 'item_006',
    code: 'MTC-LUBE-ISO68',
    name: 'Hydraulic & Forging Oil Lube ISO VG 68',
    category: 'general',
    uom: 'Drum',
    inventoryAccountCode: '1080005',
    inventoryAccountName: 'Mold & Spare Part',
    expenseAccountCode: '5100002',
    expenseAccountName: 'Consumable & Factory Supplies',
    minimumStock: 5,
    safetyStock: 10,
    standardCost: 420.00,
    standardPrice: 0,
    currency: 'USD',
    location: 'WH-CHEM-01',
    isActive: true,
    notes: 'Pelumas hidrolik press forging dan mesin CNC',
    suppliers: [
      {
        supplierId: 'sup_005',
        supplierCode: 'SUP-005',
        supplierName: 'PT Idemitsu Lube Techno Indonesia',
        price: 420.00,
        currency: 'USD',
        leadTimeDays: 3,
        isPrimary: true,
        notes: 'Daphne Super Hydro 68A Drum 200L Original'
      },
      {
        supplierId: 'sup_004',
        supplierCode: 'SUP-004',
        supplierName: 'CV Surya Teknik Mandiri',
        price: 6850000,
        currency: 'IDR',
        leadTimeDays: 2,
        isPrimary: false,
        notes: 'Ready stock gudang Jababeka Cikarang'
      }
    ]
  }
];

export const DEFAULT_PRODUCTION_PROCESSES: ProductionProcess[] = [
  {
    id: 'prs_001',
    code: 'PRS-CUT-01',
    name: 'Bar Shearing & Saw Cutting',
    workCenter: 'Shearing Machine Amada 150T',
    cycleTimeMinutes: 0.15,
    standardCapacityPerHour: 400,
    description: 'Pemotongan material round steel bar menjadi slug dengan toleransi berat ±1 gram',
    isActive: true
  },
  {
    id: 'prs_002',
    code: 'PRS-PHOS-01',
    name: 'Shot Blast & Bonderizing (Phosphate Coating)',
    workCenter: 'Chemical Dip Line & Tumbler Tank',
    cycleTimeMinutes: 25.0,
    standardCapacityPerHour: 1200,
    description: 'Pelapisan phosphating zinc & zinc stearate soap lube untuk pelumasan cold extrusion',
    isActive: true
  },
  {
    id: 'prs_003',
    code: 'PRS-CF-01',
    name: 'Cold Forging & Extrusion',
    workCenter: 'Multi-Station Cold Former 800 Ton (Komatsu)',
    cycleTimeMinutes: 0.08,
    standardCapacityPerHour: 750,
    description: 'Pembentukan profil gigi dan spline presisi tanpa pemanasan material',
    isActive: true
  },
  {
    id: 'prs_004',
    code: 'PRS-CNC-01',
    name: 'CNC Turning & Precision Machining',
    workCenter: 'CNC Lathe Brother Speedio / Mazak QT-200',
    cycleTimeMinutes: 1.20,
    standardCapacityPerHour: 50,
    description: 'Pembubutan presisi diameter luar, alur snap ring, dan chamfering',
    isActive: true
  },
  {
    id: 'prs_005',
    code: 'PRS-HEAT-01',
    name: 'Continuous Gas Carburizing Heat Treatment',
    workCenter: 'Furnace Atmosphere Sealed Quench Dichem',
    cycleTimeMinutes: 180.0,
    standardCapacityPerHour: 600,
    description: 'Pengerasan permukaan (case depth 0.8-1.0mm, hardness HRC 58-62) dan oil quench',
    isActive: true
  },
  {
    id: 'prs_006',
    code: 'PRS-QC-01',
    name: 'Final Inspection & Eddy Current Testing',
    workCenter: 'Automated 100% Sorting Table & CMM Room',
    cycleTimeMinutes: 0.25,
    standardCapacityPerHour: 240,
    description: 'Pemeriksaan dimensi gigi gear, retak mikro, dan uji kekerasan 100%',
    isActive: true
  },
  {
    id: 'prs_007',
    code: 'PRS-PACK-01',
    name: 'VCI Rust Preventive & Packaging',
    workCenter: 'Packing Line 1',
    cycleTimeMinutes: 0.50,
    standardCapacityPerHour: 120,
    description: 'Penyemprotan anti karat VCI, kantong plastik kedap udara, dan boxing karton',
    isActive: true
  }
];

export const DEFAULT_DAILY_RATES: DailyRate[] = [
  {
    id: 'drate_001',
    date: '2026-03-16',
    currency: 'USD',
    rateBI: 16285.00,
    rateKMK: 16250.00,
    source: 'KMK No. 11/KM.10/2026',
    notes: 'Kurs Tengah BI & Kepmenkeu Pajak PPN/PPh'
  },
  {
    id: 'drate_002',
    date: '2026-03-16',
    currency: 'JPY',
    rateBI: 108.65,
    rateKMK: 108.20,
    source: 'KMK No. 11/KM.10/2026',
    notes: 'Kurs Japanese Yen per 1 JPY'
  },
  {
    id: 'drate_003',
    date: '2026-03-16',
    currency: 'EUR',
    rateBI: 17680.00,
    rateKMK: 17620.00,
    source: 'KMK No. 11/KM.10/2026',
    notes: 'Kurs Euro'
  },
  {
    id: 'drate_004',
    date: '2026-03-16',
    currency: 'SGD',
    rateBI: 12210.00,
    rateKMK: 12180.00,
    source: 'KMK No. 11/KM.10/2026',
    notes: 'Kurs Singapore Dollar'
  },
  {
    id: 'drate_005',
    date: '2026-03-16',
    currency: 'CNY',
    rateBI: 2265.00,
    rateKMK: 2250.00,
    source: 'KMK No. 11/KM.10/2026',
    notes: 'Kurs Chinese Yuan Renminbi'
  },
  {
    id: 'drate_006',
    date: '2026-03-15',
    currency: 'USD',
    rateBI: 16275.00,
    rateKMK: 16250.00,
    source: 'KMK No. 10/KM.10/2026',
    notes: 'Kurs harian penutupan'
  },
  {
    id: 'drate_007',
    date: '2026-03-15',
    currency: 'JPY',
    rateBI: 108.40,
    rateKMK: 108.20,
    source: 'KMK No. 10/KM.10/2026',
    notes: 'Kurs Japanese Yen'
  }
];

export const DEFAULT_PURCHASE_REQUESTS: PurchaseRequest[] = [
  {
    id: 'pr_2026_001',
    prNumber: 'PR/2026/03/001',
    date: '2026-03-10',
    deptCode: 'ENG',
    deptName: 'Production Engineering',
    requesterName: 'Ahmad Fauzi',
    purpose: 'Pengadaan Punch Die Cold Forging 24T Gear untuk persiapan produksi Mass Pro Jatco',
    priority: 'high',
    status: 'approved',
    totalAmountEstimated: 1700.00,
    currency: 'USD',
    approvedBy: 'Director of Operation',
    approvalDate: '2026-03-12',
    linkedPoNumber: 'PO/2026/03/001',
    notes: 'Disetujui untuk diteruskan ke proses PO vendor CV Surya Teknik',
    createdAt: '2026-03-10',
    updatedAt: '2026-03-12',
    items: [
      {
        id: 'pr_item_1',
        itemCode: 'MLD-CF-P24T',
        itemName: 'Punch Die Cold Forging 24T Gear (Tungsten Carbide)',
        description: 'Tungsten Carbide grade G5, hardness HRA 90, drawing no. DWG-ENG-24100',
        qty: 2,
        uom: 'Set',
        estimatedPrice: 850.00,
        currency: 'USD',
        totalEstimated: 1700.00,
        requiredDate: '2026-03-28',
        notes: 'Lead time vendor 14 hari kerja'
      }
    ]
  },
  {
    id: 'pr_2026_002',
    prNumber: 'PR/2026/03/002',
    date: '2026-03-12',
    deptCode: 'PC',
    deptName: 'Production Control',
    requesterName: 'Dewi Lestari',
    purpose: 'Kebutuhan Raw Material Steel Rod S45C untuk alokasi produksi transmisi kuartal 2',
    priority: 'normal',
    status: 'submitted',
    totalAmountEstimated: 14500.00,
    currency: 'USD',
    notes: 'Menunggu approval manager finance',
    createdAt: '2026-03-12',
    updatedAt: '2026-03-12',
    items: [
      {
        id: 'pr_item_2',
        itemCode: 'RM-S45C-D28',
        itemName: 'Round Steel Bar S45C Dia 28mm x 6000mm',
        description: 'Certificate of Analysis (Mill Sheet) wajib disertakan',
        qty: 10000,
        uom: 'Kg',
        estimatedPrice: 1.45,
        currency: 'USD',
        totalEstimated: 14500.00,
        requiredDate: '2026-04-05',
        notes: 'Pengiriman bertahap 2 rit'
      }
    ]
  },
  {
    id: 'pr_2026_003',
    prNumber: 'PR/2026/03/003',
    date: '2026-03-14',
    deptCode: 'MTC',
    deptName: 'Maintenance',
    requesterName: 'Budi Raharjo',
    purpose: 'Penggantian oli pelumas mesin forging Komatsu 800T berkala',
    priority: 'urgent',
    status: 'draft',
    totalAmountEstimated: 1680.00,
    currency: 'USD',
    notes: 'Draf usulan maintenance preventive',
    createdAt: '2026-03-14',
    updatedAt: '2026-03-14',
    items: [
      {
        id: 'pr_item_3',
        itemCode: 'MTC-LUBE-ISO68',
        itemName: 'Hydraulic & Forging Oil Lube ISO VG 68',
        description: 'Kemasan drum 200 Liter, Idemitsu Daphne Super Hydro 68A',
        qty: 4,
        uom: 'Drum',
        estimatedPrice: 420.00,
        currency: 'USD',
        totalEstimated: 1680.00,
        requiredDate: '2026-03-22',
        notes: 'Segera diproses'
      }
    ]
  }
];

export const DEFAULT_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: 'po_2026_001',
    poNumber: 'PO/2026/03/001',
    date: '2026-03-13',
    prNumber: 'PR/2026/03/001',
    supplierCode: 'SUP-004',
    supplierName: 'CV Surya Teknik Mandiri',
    supplierAddress: 'Jl. Raya Industri Pasir Gombong No. 88, Cikarang Utara, Bekasi',
    supplierContact: 'Hendra Gunawan',
    supplierEmail: 'suryateknik.cikarang@gmail.com',
    supplierPhone: '+62 21 89831102',
    deliveryDate: '2026-03-28',
    paymentTerms: 'NET 14',
    currency: 'USD',
    rate: 16273.56,
    subtotal: 1700.00,
    taxPercent: 11,
    taxAmount: 187.00,
    grandTotal: 1887.00,
    grandTotalUSD: 1887.00,
    status: 'sent',
    deliveryAddress: 'Kawasan Industri GIIC Blok C-1, Cikarang Pusat, Bekasi - Loading Dock MTC',
    notes: 'Tolong konfirmasi jadwal pengiriman & uji coba dimensi Dies sebelum dikirim',
    createdAt: '2026-03-13',
    updatedAt: '2026-03-14',
    items: [
      {
        id: 'po_line_1',
        itemCode: 'MLD-CF-P24T',
        itemName: 'Punch Die Cold Forging 24T Gear (Tungsten Carbide)',
        description: 'Tungsten Carbide grade G5, hardness HRA 90, drawing no. DWG-ENG-24100',
        qty: 2,
        uom: 'Set',
        unitPrice: 850.00,
        totalPrice: 1700.00,
        notes: 'Sesuai spek PR/2026/03/001'
      }
    ]
  },
  {
    id: 'po_2026_002',
    poNumber: 'PO/2026/02/015',
    date: '2026-02-18',
    supplierCode: 'SUP-002',
    supplierName: 'PT Daido Steel Indonesia',
    supplierAddress: 'Kawasan Industri MM2100 Blok C-3, Cikarang Barat, Bekasi',
    supplierContact: 'Kenji Takahashi / Linda W.',
    supplierEmail: 'order@daido-steel.co.id',
    supplierPhone: '+62 21 8972100',
    deliveryDate: '2026-03-05',
    paymentTerms: 'NET 30',
    currency: 'USD',
    rate: 16273.56,
    subtotal: 8100.00,
    taxPercent: 0,
    taxAmount: 0.00,
    grandTotal: 8100.00,
    grandTotalUSD: 8100.00,
    status: 'received',
    deliveryAddress: 'Gudang Raw Material PT SmartBudget Manufacturing Cikarang',
    notes: 'Kawasan Berikat PPN Tidak Dipungut. Barang sudah diterima lengkap di gudang RM.',
    createdAt: '2026-02-18',
    updatedAt: '2026-03-06',
    items: [
      {
        id: 'po_line_2',
        itemCode: 'RM-SCR420-D32',
        itemName: 'Steel Rod SCr420H Dia 32mm Annealed',
        description: 'Standard JIS G4053 SCr420H Annealed, Heat No. D-99120',
        qty: 5000,
        uom: 'Kg',
        unitPrice: 1.62,
        totalPrice: 8100.00,
        notes: 'Mill Certificate terlampir'
      }
    ]
  }
];
