import React from 'react';
import {
  Home,
  LayoutGrid,
  Layers,
  DollarSign,
  Building2,
  BookOpen,
  ArrowLeftRight,
  UploadCloud,
  Wallet,
  Users,
  LogOut,
  ShieldCheck,
  Settings,
  History,
  TrendingUp,
  Box,
  Boxes,
  ChevronDown,
  ChevronRight,
  FileSpreadsheet,
  ShoppingCart,
  Truck,
  Briefcase,
  PackageCheck,
  Workflow,
  CircleDollarSign,
  Factory,
  FileText,
  Code2,
  Terminal,
  Cpu,
  Database,
  Sliders,
  Wrench,
  Sparkles,
  Table,
  FolderTree,
  PlusCircle,
  FileCode,
  FormInput,
  KeyRound,
  FileBox,
  HardDrive,
  GitBranch,
  Search,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  FolderPlus,
  RefreshCw,
  Folder,
  Tag,
  Kanban,
  ClipboardList
} from 'lucide-react';

export const ICON_REGISTRY: Record<string, React.ComponentType<{ className?: string; size?: number }>> = {
  Home,
  LayoutGrid,
  Layers,
  DollarSign,
  Building2,
  BookOpen,
  ArrowLeftRight,
  UploadCloud,
  Wallet,
  Users,
  LogOut,
  ShieldCheck,
  Settings,
  History,
  TrendingUp,
  Box,
  Boxes,
  ChevronDown,
  ChevronRight,
  FileSpreadsheet,
  ShoppingCart,
  Truck,
  Briefcase,
  PackageCheck,
  Workflow,
  CircleDollarSign,
  Factory,
  FileText,
  Code2,
  Terminal,
  Cpu,
  Database,
  Sliders,
  Wrench,
  Sparkles,
  Table,
  FolderTree,
  PlusCircle,
  FileCode,
  FormInput,
  KeyRound,
  FileBox,
  HardDrive,
  GitBranch,
  Search,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  FolderPlus,
  RefreshCw,
  Folder,
  Tag,
  Kanban,
  ClipboardList
};

export const AVAILABLE_ICON_NAMES = Object.keys(ICON_REGISTRY);

export function getDynamicIcon(name?: string, className = 'w-4 h-4', size?: number): React.ReactNode {
  if (!name) {
    return <Layers className={className} size={size} />;
  }
  const Component = ICON_REGISTRY[name] || Layers;
  return <Component className={className} size={size} />;
}
